// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/Content.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ExportModal: typeof import('./src/components/exportModal.vue')['default']
    HoverArea: typeof import('./src/components/HoverArea.vue')['default']
    HoverCorner: typeof import('./src/components/HoverCorner.vue')['default']
    'IGrommetIcons:documentWord': typeof import('~icons/grommet-icons/document-word')['default']
    'IMdi:arrowTopLeftThinCircleOutline': typeof import('~icons/mdi/arrow-top-left-thin-circle-outline')['default']
    'IMdi:filePdf': typeof import('~icons/mdi/file-pdf')['default']
    'IMdi:fileWord': typeof import('~icons/mdi/file-word')['default']
    'IMdi:spellcheck': typeof import('~icons/mdi/spellcheck')['default']
    'IMdi:themeLightDark': typeof import('~icons/mdi/theme-light-dark')['default']
    'IRi:settings3Line': typeof import('~icons/ri/settings3-line')['default']
    NCard: typeof import('naive-ui')['NCard']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NH2: typeof import('naive-ui')['NH2']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSlider: typeof import('naive-ui')['NSlider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Options: typeof import('./src/components/Options.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    WordCount: typeof import('./src/components/WordCount.vue')['default']
  }
}

export { }
